### ISSUE TITLE
Train "image and one modality"?

### ISSUE THREAD

**Issue by pengzhao-life** [fabawi/ImageBind-LoRA#16]
@fabawi  Thanks for sharing the great work! If I want to train image, text, and depth, I need to train image with each modality, i.e. image-text, image-depth, respectively?

**Comment by fabawi** [comment]
@pengzhao-life according to the ImageBind paper, yes, the image is what you would contrast with all modalities. In this implementation, It is dependent on the dataset generator where the first modality is vision-based or not. In the toy example provided, I hardcode the first and second modalities in the dataset:

https://github.com/fabawi/ImageBind-LoRA/blob/d10a4e09d332a87ce323e3d99c6907583ffd9322/datasets/dreambooth.py#L51

Note that you can set the first and second modalities however you'd like; it won't break the training process but might **not** yield good results.

P.S.: I would recommend checking out the [class_aware](https://github.com/fabawi/ImageBind-LoRA/tree/class_aware) branch of this repo, as the training is more aligned with the original ImageBind contrastive learning paradigm.
