### ISSUE TITLE
Adjust the number of trainable parameters.

### ISSUE THREAD

**Issue by alvinkimata** [fabawi/ImageBind-LoRA#2]
Is there a way to increase or decrease the number of trainable parameters using LoRA?

**Comment by fabawi** [comment]
you can change the number of LoRA layers by changing --lora_layer_idxs or adding more modalities. You can also modify the LoRA rank. Other than that, you can switch to linear probing. I did not implement any targetted layer training, but following the code provided, you could easily do so by setting their `requires_grad = True` and everything else to `False`. This should give you an idea how to do it:
https://github.com/fabawi/ImageBind-LoRA/blob/127d8c4a03221bb187a02f9c1076e97d7e4b6c31/train.py#L87
