### ISSUE TITLE
Great work! Can you explain how to make inference in example.py? Thanks

### ISSUE THREAD

**Issue by NateDong72** [fabawi/ImageBind-LoRA#3]

**Comment by fabawi** [comment]
I'm not sure what you'd like to do exactly. If you'd like to know which representation in one modality is closest to another, say the sound of a dog vs. the word "dog", you take the argmax of the any of the lines     e.g., 

```
torch.argmax(torch.softmax(embeddings[ModalityType.VISION] @ embeddings[ModalityType.TEXT].T * (lora_factor if lora else 1), dim=-1), dim=-1)
```

This returns a tensor of indices, where the element indicates the image index, and returned numbers are the text index. In the case of LoRA, the returned indices are:

```
tensor([2, 1, 2, 3, 4, 5])
```

corresponding to:

```
"dog3", "car", "dog3", "dog5", "dog8", "grey_sloth_plushie"
```

You can acquire the latter by:

```
text_pred = torch.argmax(torch.softmax(embeddings[ModalityType.VISION] @ embeddings[ModalityType.TEXT].T * (lora_factor if lora else 1), dim=-1), dim=-1)
print([text_list[i] for i in text_pred])
```

This will behave like a class predictor for images, where you feed in an image/s and you get the text as output

**Comment by WilTay1** [comment]
Thank you for the reply. 
How do you map the indices  to "dog3", "car", "dog5" ...   is there any list or map? 
![image](https://github.com/fabawi/ImageBind-LoRA/assets/133484736/f6b89b10-8a2d-4436-bb96-9c8ffa141e9c)

**Comment by fabawi** [comment]
yes, that's what text_list contains. These are some randomly chosen classes that match the text you trained or fine-tuned the model on. The original model was trained on datasets containing image/text pairs with the text being "car" for example. In the dreambooth dataset, I fine-tune the model on the directory names of each of the images corresponding to some being "dog3", "dog5" etc. The idea is that during inference you specify which class/text you want to predict, and you see how much your other modality (e.g., image) matches any of the text items you provided in text_list. The highest matching "text" would then be the predicted label for each of the images you provide.In practice, you calculate the embeddings of the texts ("dog2", "car", "bird", ...) and then you compare it to each image you want to test
