### ISSUE TITLE
Question about lora.py

### ISSUE THREAD

**Issue by beitong95** [fabawi/ImageBind-LoRA#4]
Hi, thanks for the amazing work for adapting LoRA on ImageBind. 

I have one question. In lora.py line 120 should it be `blk.attn.q_proj_weight` instead of `bulk.attn.proj_q`. The same change should  also be used in line 121.

**Comment by fabawi** [comment]
Thanks for pointing it out, you are right. The latest version was not pushed earlier, I'm surprised this even ran! It has been updated
